crossbar:
  image: gosmart/crossbar
  ports:
    - "8080:8080"
  volumes:
    - ./web:/.crossbar
glossia:
  image: gosmart/glossia
  environment:
    CROSSBAR_PORT: 8080
    CROSSBAR_HOST: crossbar
    DOCKERLAUNCH_SOCKET: /dockerlaunch.sock
    GLOSSIA_SIMULATION_DIRECTORY: /simdata
  links:
    - crossbar
  volumes:
    - /var/run/dockerlaunch/dockerlaunch.sock:/dockerlaunch.sock
    - ./simulations:/var/run/glossia
  volumes_from:
    - data
  command: default
data:
  image: gosmart/glossia
  entrypoint: /bin/true
  volumes:
    - ./simdata:/simdata
    - ./transferrer:/tmp/gssa-transferrer
